### ISSUE TITLE
which page should be default (just after log in)?

### ISSUE THREAD

**Issue by hidehiro98** [hidehiro98/airflow_beta#24]

**Comment by db0sch** [comment]
dashboard -> received requests. i think.
That's the requests the user needs to work on.

**Comment by hidehiro98** [comment]
Yes, but for someone mainly creates requests, it should be sent_requests page, I think.
How do you think about it?

**Comment by db0sch** [comment]
that's the problem. you can't have condition in the routes.
But, maybe, you can think of a simple dashboard -> which would say for exemple:

- 5 requests received
- 10 requests sent still pending
- 2 requests sent commented
... etc

That would be your root_page.
that's just an idea. What do you think?
(if you want to do it, you have to design it.).

Otherwise, I would just go for the simple solution: received_requests.
And you'll see with your clients.

**Comment by hidehiro98** [comment]
Yes, creating simple dashboard is good idea, but I think we don't need it right now because dashboard is not mandatory.

How about the set sent_requests page as a first page, because user who mainly creates requests access this service more often I think.

**Comment by hidehiro98** [comment]
I decided that received page is set to the default page because as you said it is natural for users.
I want reduce user's stress as less as possible.
